### PR TITLE
Fix https://github.com/dominictarr/npmd-config/issues/8

### PR DESCRIPTION
**Pull request by scv119**
I think by this way we could 
1) has default values
2) first overwrite default values by npmrc
3) then overwrite them by arguments in commandline

### CODE REVIEW

**Comment by dominictarr** [comment]
Hmm, no this isn't the right solution. We need null defaults to know if that option is _unset_.
rc needs that, so that it can fall through to the configuration files. The bug here is in minimist. When you set a option as boolean type, and then set a value, it makes it into an array.

**Comment by dominictarr** [comment]
here is the correct fix: https://github.com/substack/minimist/pull/45

**Comment by scv119** [comment]
I see, not familiar with minimist so don't know this behavior. Thank you for the fix!

**Comment by dominictarr** [comment]
okay this is fixed in npmd-config@1.2.3
reinstalling npmd should get you that version of npmd-config

**Pull request closed without merging**
